name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          # Dummy DATABASE_URL for build time (not used in frontend)
          DATABASE_URL: 'postgresql://dummy:dummy@localhost:5432/dummy'
          # Optional: Custom API URL for production
          VITE_API_URL: ${{ secrets.VITE_API_URL || '' }}
      
      - name: Deploy to Cloudflare Pages
        # Only deploy on main branch
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID || '523d80131d8cba13f765b80d6bb9e096' }}
          projectName: mcp-server-manager
          directory: dist/public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          wranglerVersion: '3'
      
      - name: Upload build artifacts
        # Always upload artifacts for debugging
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 7