name: PR Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run check
        continue-on-error: true
      
      - name: Build application
        id: build
        run: npm run build
        env:
          NODE_ENV: production
          DATABASE_URL: 'postgresql://dummy:dummy@localhost:5432/dummy'
      
      - name: Verify build output
        if: success()
        run: |
          echo "✅ Build completed successfully"
          echo "Checking build artifacts..."
          if [ -d "dist" ]; then
            echo "dist/ directory exists"
            ls -la dist/
          fi
          if [ -d "dist/public" ]; then
            echo "dist/public/ directory exists"
            ls -la dist/public/
          fi
      
      - name: Build Summary
        if: always()
        run: |
          if [ "${{ steps.build.outcome }}" == "success" ]; then
            echo "✅ Build completed successfully!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Build Artifacts" >> $GITHUB_STEP_SUMMARY
            echo "- Frontend: dist/public/" >> $GITHUB_STEP_SUMMARY
            echo "- Server: dist/index.js" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Build failed!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please check the logs above for details." >> $GITHUB_STEP_SUMMARY
          fi